"""add category, location, insurance and delivery to items

Revision ID: cbec6a699d53
Revises: 4fa485c1098e
Create Date: 2026-02-20 09:20:50.039941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbec6a699d53'
down_revision: Union[str, Sequence[str], None] = '4fa485c1098e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('items', sa.Column('has_insurance', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('has_fast_delivery', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'has_fast_delivery')
    op.drop_column('items', 'has_insurance')
    op.drop_column('items', 'location')
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
